version: '3.9'

services:
  mysql:
    image: mysql:8.2
    container_name: mysql_container
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_application
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: mysecretpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
    driver: local
